services:
  db:
    image: postgres:16-alpine
    container_name: castramais-db
    restart: always
    environment:
      POSTGRES_USER: castramais
      POSTGRES_PASSWORD: c9dd730d4262ee476d021e72d81597b5200c8e52eb5e721940f9fb246fe641b1
      POSTGRES_DB: castramais
    volumes:
      - castramais_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U castramais"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - castramais-network

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: castramais-app
    restart: always
    ports:
      - "80:3000"
    environment:
      DATABASE_URL: postgresql://castramais:c9dd730d4262ee476d021e72d81597b5200c8e52eb5e721940f9fb246fe641b1@db:5432/castramais
      NEXTAUTH_SECRET: d28ae335f31f21d9f5eff6a210436314d5b61912fd5add3e3b88302dbd63f868
      NEXTAUTH_URL: https://castramais.odois.com.br
      NODE_ENV: production
      ADMIN_EMAIL: admin@castramais.com.br
      ADMIN_PASSWORD: 2l2SjbeeFfEoB66G
      # Evolution API (WhatsApp)
      EVOLUTION_API_URL: https://evo.odois.com.br
      EVOLUTION_API_KEY: a87ad2de419f678eccfdd25962db593cb6cbb7523a44dd57fbc9bfcbd938d1b1
      EVOLUTION_INSTANCE: castramais
      # SMTP (Email) - Ethereal para testes
      SMTP_HOST: smtp.ethereal.email
      SMTP_PORT: 587
      SMTP_USER: ardith33@ethereal.email
      SMTP_PASS: EM7g7AjuTvNjCV9Fsy
      SMTP_FROM: noreply@castramais.com.br
    depends_on:
      db:
        condition: service_healthy
    networks:
      - castramais-network

networks:
  castramais-network:
    driver: bridge

volumes:
  castramais_db_data:
